[project]
name = "chatgpt2api"
version = "1.2.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cryptography>=41.0.0",
    "curl-cffi>=0.15.0",
    "fastapi>=0.136.0",
    "pillow>=12.2.0",
    "pynacl>=1.5.0",
    "pybase64>=1.4.3",
    "python-multipart>=0.0.26",
    "requests>=2.32.0",
    "tiktoken>=0.12.0",
    "uvicorn>=0.44.0",
    "httpx>=0.27.0",
    "python-pptx>=1.0.2,<2",
    "psd-tools>=1.11,<2",
    "opencv-python-headless>=4.10,<5",
]
